project:
  type: book
  output-dir: .

book:
  title: "ShapleyVIC: Shapley Variable Importance Cloud for Interpretable Machine Learning"
  author: "Yilin Ning, Chenglin Niu, Mingxuan Li, Siqi Li, Nan Liu"
  date: today
  date-format: iso
  chapters:
    - index.qmd
    - data.qmd
    - shapleyvic.qmd
    - autoscore_shapleyvic.qmd
    - autoscore_shapleyvic_reprod.qmd
  downloads: pdf

format:
  html:
    theme: simplex
    css: custom.css
    code-copy: true
    number-depth: 3
  pdf:
    documentclass: scrreprt
